In [6]:
import pandas as pd

# Load the excel sheets
Sem_1_2023 = pd.ExcelFile('Sem_1_2023.xlsx')
Sem_2_2023 = pd.ExcelFile('Sem_2_2023.xlsx')


S1_2023_total_df = pd.read_excel(Sem_1_2023, 'Total')
S1_2023_game_stats_df = pd.read_excel(Sem_1_2023, 'Game Stats')
S1_2023_goalie_stats_df = pd.read_excel(Sem_1_2023, 'Goalie Stats')


S2_2023_total_df = pd.read_excel(Sem_2_2023, 'Total')
S2_2023_game_stats_df = pd.read_excel(Sem_2_2023, 'Game Stats')

In [7]:
# Combine the 'Total' data from both semesters
total_df = pd.concat([S1_2023_total_df, S2_2023_total_df], ignore_index=True)

# Group by player and sum their stats to get total performance across both semesters
total_season_df = total_df.groupby('Player').sum().reset_index()

In [3]:
total_season_df.head()

,Game,Player,Goals,Assists,Shots,Shots on Target,Shot Conversion (Total),Shot Conversion (on Target),Shots on Target %,Fouls,...,Succesful Tackles,Removed from Danger,Headers,Unnamed: 15,Game.1,Goals Against,Corners,Converted Corners,Corners Against,Converted Corners Against
0,1,Kanishka,2,1,4,2,0.500000,1.000000,0.500000,0,...,6,1,0,NaN,1,3.0,3.0,1.0,1.0,0.0
1,1,Matthew,4,3,8,5,0.500000,0.800000,0.625000,0,...,5,2,0,NaN,2,5.0,8.0,1.0,1.0,0.0
2,1,Remy,1,1,7,3,0.142857,0.333333,0.428571,0,...,1,1,0,NaN,3,3.0,10.0,0.0,2.0,0.0
3,1,Abhinav,2,2,7,4,0.285714,0.500000,0.571429,0,...,5,2,0,NaN,4,3.0,6.0,0.0,3.0,0.0
4,1,Jeremy,1,1,3,1,0.333333,1.000000,0.333333,0,...,2,1,0,NaN,5,5.0,4.0,1.0,4.0,0.0