In [17]:
import pandas as pd

# Load the excel sheets
Sem_1_2023 = pd.ExcelFile('Sem_1_2023.xlsx')
Sem_2_2023 = pd.ExcelFile('Sem_2_2023.xlsx')


S1_2023_total_df = pd.read_excel(Sem_1_2023, 'Total')
S1_2023_game_stats_df = pd.read_excel(Sem_1_2023, 'Game Stats')

S2_2023_total_df = pd.read_excel(Sem_2_2023, 'Total')
S2_2023_game_stats_df = pd.read_excel(Sem_2_2023, 'Game Stats')

### Cleaning The Data

In [22]:
# Columns to remove from S1_2023_total_df
columns_to_remove_total = ['Unnamed: 16', 'Matches', 'Goals Against', 'Corners', 'Converted Corners', 
                           'Corners Against', 'Converted Corners Against', 'Goals Conceded Per Match', 
                           'Goals Per Match', 'Unnamed: 25', 'TOTALS', 'Unnamed: 27', 'Unnamed: 28', 
                           'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32']

# Dropping the columns
S1_2023_total_df_cleaned = S1_2023_total_df.drop(columns=columns_to_remove_total)

# Columns to remove from S1_2023_game_stats_df
columns_to_remove_game_stats = ['Unnamed: 15', 'Game.1', 'Goals Against', 'Corners', 'Converted Corners', 
                                'Corners Against', 'Converted Corners Against']

# Dropping the columns
S1_2023_game_stats_df_cleaned = S1_2023_game_stats_df.drop(columns=columns_to_remove_game_stats)

In [23]:
S1_2023_game_stats_df_cleaned.head()

,Game,Player,Goals,Assists,Shots,Shots on Target,Shot Conversion (Total),Shot Conversion (on Target),Shots on Target %,Fouls,Woodwork Hit,Blocked Shots,Succesful Tackles,Removed from Danger,Headers
0,1,Kanishka,2,1,4,2,0.500000,1.000000,0.500000,0,0,0,6,1,0
1,1,Matthew,4,3,8,5,0.500000,0.800000,0.625000,0,1,1,5,2,0
2,1,Remy,1,1,7,3,0.142857,0.333333,0.428571,0,1,0,1,1,0
3,1,Abhinav,2,2,7,4,0.285714,0.500000,0.571429,0,1,0,5,2,0
4,1,Jeremy,1,1,3,1,0.333333,1.000000,0.333333,0,0,0,2,1,0